"""Approved authored walk/run clips plus the unchanged native-compatible steps.

Classic (Mannequiny) and the approved Natural/Fighter (CMU capture) styles
supply local bone rotations and hip weight shift. Runtime ground_root_motion retargets that shift after native
conversion using the current character's own root and leg length. Other bones
retain native bind translations, so bodies are never stretched to Goku's mesh.
See assets/licenses/Mannequiny.txt and CMU-Motion-Capture.txt for the separate
animation-data terms and attribution.

Only ground actions 13/14, animation IDs 2..9 use authored motion. IDs10/11 and
the STOP set's8/9 keep the previous sidestep/brake clips byte for byte. Native
flight, combat, jumps and cinematics are outside the runtime hook's guards.

Native format: flags0x61, frame count,71 track offsets. Type1 channels hold
packed quaternions and u16 times; the marked type0 root holds normalized XYZ,
u32 times and quaternion. The high marker bits leave native bit0 semantics
unchanged. Immutable root curves repair native body conversion before playback.
Literal byte-pair packing and all generated bytes are deterministic.
"""
import functools
import hashlib
import math
import struct
import ground_motion

BONES = 71              # native track table size
TRACKED = range(1, 55)  # bones 1..54, like native clips
FLAGS = 0x61            # native anims 2..11
KEYS = 33               # one key every 1/32 cycle: smoother feet/arms at fast playback, still within the guest pool
STOP_KEYS = 9
RUN, WALK, BOUND_RUN, BOUND_WALK, STOP = 0, 1, 2, 3, 4
GAITS = ('run', 'walk', 'bound-run', 'bound-walk', 'stop')
SETS = (RUN, WALK, BOUND_RUN, BOUND_WALK)
WALKING = (WALK, BOUND_WALK)
IDS = tuple(range(2, 12))

# Parent of every standard-biped bone 0..54 (Goku; release check: --scan-parents against every bank).
PARENTS = (-1, 0, 1, 2, 3, 4, 5, 6, 3, 8, 9, 10, 3, 12, 13, 14, 3, 16, 17, 18, 19, 20, 21, 21, 23, 21, 25, 21, 27,
           21, 29, 21, 17, 32, 33, 34, 35, 35, 37, 35, 39, 35, 41, 35, 43, 35, 17, 46, 47, 47, 47, 47, 0, 0, 0)
# Relaxed fist: local rotations (x, y, z, w) of the fingers, Goku anim 3 frame 0 (--extract-fist).
FIST = {
    22: (-0.016961, 0.116304, -0.143299, 0.982675), 23: (0.0, 0.0, -0.534987, 0.844860),
    24: (0.0, 0.0, -0.601586, 0.798808), 25: (0.0, 0.0, -0.480022, 0.877256),
    26: (0.0, 0.0, -0.601586, 0.798808), 27: (0.0, 0.0, -0.520394, 0.853926),
    28: (0.0, 0.0, -0.601586, 0.798808), 29: (0.0, 0.0, -0.545314, 0.838232),
    30: (0.0, 0.0, -0.601586, 0.798808), 31: (0.0, 0.0, 0.0, 1.0),
    36: (-0.016961, -0.116306, 0.143297, 0.982675), 37: (0.0, 0.0, 0.534986, 0.844861),
    38: (0.0, 0.0, 0.601584, 0.798809), 39: (0.0, 0.0, 0.480021, 0.877257),
    40: (0.0, 0.0, 0.601584, 0.798809), 41: (0.0, 0.0, 0.520393, 0.853927),
    42: (0.0, 0.0, 0.601584, 0.798809), 43: (0.0, 0.0, 0.545313, 0.838233),
    44: (0.0, 0.0, 0.601584, 0.798809), 45: (0.0, 0.0, 0.0, 1.0)}
# Leg and arm bones (thigh, knee, ankle) / (shoulder, elbow, wrist) per side; the right side is model -X.
LEGS = {'R': (9, 10, 11), 'L': (13, 14, 15)}
ARMS = {'R': (19, 20, 21), 'L': (33, 34, 35)}
PELVIS, SPINE, CHEST, NECK, HEAD = 3, 16, 17, 46, 47
# Goku's right-leg rest translations (bones 2, 3, 8..11, Y down), for the planted-foot speed (STANCE_SPEED).
GOKU_LEG = {2: (0.0, -10.087, -0.608), 3: (0.0, 0.0, 0.0), 8: (-0.617, -0.141, 0.17), 9: (-0.332, 0.344, -0.1),
            10: (-0.517, 4.066, 0.417), 11: (-0.534, 4.748, 0.495)}
GOKU_LEG_LENGTH = 8.923             # |10| + |11|: the leg length of ground_legs (thigh + shin)
# Frame counts (60 Hz units).
LOOP_FRAMES = {RUN: 38, WALK: 62, BOUND_RUN: 38, BOUND_WALK: 62}
FRAMES = {}
for _g in SETS:
    for _a in (2, 3, 4, 5, 6, 7): FRAMES[(_g, _a)] = LOOP_FRAMES[_g]
    for _a in (8, 9, 10, 11): FRAMES[(_g, _a)] = 48  # preserve native close-range layer timing
STOP_FRAMES = 16                    # 8 ticks
for _a in IDS: FRAMES[(STOP, _a)] = STOP_FRAMES if _a in (8, 9) else FRAMES[(RUN, _a)]
# Entries that point at another set's clip (one copy in RAM): every set's 8..11 are set 0's, the brake's 2..7 and
# 10/11 are set 0's (only its 8/9 are its own).
SHARED = {(g, a): (RUN, a) for g in (WALK, BOUND_RUN, BOUND_WALK) for a in (8, 9, 10, 11)}
SHARED.update({(STOP, a): (RUN, a) for a in IDS if a not in (8, 9)})
SHARED[(STOP, 9)] = (STOP, 8)
STEP = 16.0             # sidestep: thigh roll (degrees) with the feet furthest apart
# Stance (foot on the ground) is leg phase 0 .. STANCE (a key time); the left leg runs half a cycle behind the
# right. Through the stance the thigh turns linearly from SWEEP to -SWEEP degrees.
STANCE = {RUN: 6/16, WALK: 10/16, BOUND_RUN: 5/16, BOUND_WALK: 9/16}
SWEEP = {RUN: 40.0, WALK: 22.5, BOUND_RUN: 46.0, BOUND_WALK: 30.0}
STANCE_KNEE_MAX = 12.0
# Upper-body turn of the 4..7 and 10/11 variants (degrees about the vertical; positive = toward the body's right).
TURN = {SPINE: 25.0, CHEST: 25.0, NECK: 20.0, HEAD: 20.0}
BANK = {SPINE: 3.0, CHEST: 3.0}        # lean into the circle, toward the target side
TURNED = {4: (2, +1), 5: (3, +1), 6: (2, -1), 7: (3, -1)}
SIDESTEP = {10: -1, 11: +1}             # +1: toward the body's right (model -X)

# Gait curves, (leg phase, degrees), interpolated with a cosine ease between points (no overshoot). The thigh
# (positive = forward) is linear through the stance (SWEEP) and follows its points through the swing; knee
# flexion; desired foot pitch relative to the pelvis (positive = toe down). The ankle counters the thigh/knee,
# rather than adding this pitch to them: otherwise the lead boot points skyward and the rear boot folds under.
# Upper body: spine/chest lean, arm swing, elbow. Running references Infinite World's Pursuing Raditz movement
# (the supplied video, 10:50..13:17): forward lean and compact, bent-arm pumping; walking stays more upright.
CURVES = {
    RUN: dict(thigh=((.375, -40), (.5, -20), (.66, 32), (.8, 58), (.92, 46), (1, 40)),
              knee=((0, 4), (.18, 11), (.375, 8), (.5, 70), (.62, 96), (.76, 66), (.9, 18), (1, 4)),
              ankle=((0, -6), (.2, 0), (.375, 24), (.5, 30), (.7, 5), (.9, -8), (1, -6)),
              lean=(25.0, 15.0), head=-33.0, arm_down=83.0, arm_swing=32.0, arm_forward=9.0, elbow=(70.0, 86.0),
              pelvis=4.0, chest=3.0),
    WALK: dict(thigh=((.625, -22.5), (.74, -10), (.86, 18), (.94, 29), (1, 22.5)),
               knee=((0, 3), (.15, 10), (.45, 4), (.625, 9), (.72, 40), (.8, 45), (.9, 15), (1, 3)),
               ankle=((0, -8), (.15, 0), (.5, 5), (.625, 15), (.72, 10), (.85, -5), (1, -8)),
               lean=(2.0, 1.5), head=-3.0, arm_down=84.0, arm_swing=16.0, arm_forward=2.0, elbow=(16.0, 24.0),
               pelvis=2.5, chest=2.0),
    BOUND_RUN: dict(thigh=((.3125, -46), (.44, -22), (.6, 40), (.76, 66), (.9, 54), (1, 46)),
                    knee=((0, 6), (.15, 12), (.3125, 10), (.44, 82), (.58, 108), (.74, 76), (.9, 22), (1, 6)),
                    ankle=((0, -8), (.16, 0), (.3125, 26), (.44, 34), (.66, 6), (.9, -10), (1, -8)),
                    lean=(26.0, 16.0), head=-35.0, arm_down=82.0, arm_swing=35.0, arm_forward=10.0,
                    elbow=(72.0, 88.0), pelvis=4.5, chest=3.5),
    BOUND_WALK: dict(thigh=((.5625, -30), (.68, -14), (.82, 24), (.92, 36), (1, 30)),
                     knee=((0, 3), (.15, 10), (.4, 5), (.5625, 10), (.66, 48), (.76, 52), (.88, 18), (1, 3)),
                     ankle=((0, -8), (.15, 0), (.45, 6), (.5625, 16), (.68, 12), (.84, -6), (1, -8)),
                     lean=(3.0, 2.0), head=-4.0, arm_down=83.0, arm_swing=19.0, arm_forward=3.0, elbow=(18.0, 26.0),
                     pelvis=3.0, chest=2.5)}
# ------------------------------------------------------------------------------------------ quaternions

def qmul(a, b):
    ax, ay, az, aw = a; bx, by, bz, bw = b
    return (aw*bx + ax*bw + ay*bz - az*by, aw*by - ax*bz + ay*bw + az*bx,
            aw*bz + ax*by - ay*bx + az*bw, aw*bw - ax*bx - ay*by - az*bz)


def qconj(q):
    return (-q[0], -q[1], -q[2], q[3])


def qnorm(q):
    n = math.sqrt(sum(v*v for v in q))
    return tuple(v/n for v in q)


def qaxis(axis, degrees):
    half = math.radians(degrees)/2
    s = math.sin(half)
    return (axis[0]*s, axis[1]*s, axis[2]*s, math.cos(half))


def qrot(q, v):
    return qmul(qmul(q, (v[0], v[1], v[2], 0.0)), qconj(q))[:3]


def encode_quat(q):
    """Native packed quaternion (256E00): the largest component is dropped (made positive), the other three are
    20-bit fixed point in [-1/sqrt2, 1/sqrt2]."""
    q = qnorm(q)
    i = max(range(4), key=lambda k: (abs(q[k]), -k))
    if q[i] < 0: q = tuple(-v for v in q)
    scale, root2 = 9.536752259009518e-7, 1.4142135381698608
    packed = i << 60
    for k, v in enumerate(q[j] for j in range(4) if j != i):
        raw = int(math.floor((v/root2 + .5)/scale + .5))
        packed |= max(0, min(0xFFFFF, raw)) << (20*k)
    return packed


# ------------------------------------------------------------------------------------------ poses

def ease(points, x):
    """Cosine-eased piecewise curve through (x, y) points sorted by x, for x in [points[0].x, points[-1].x]."""
    for (x0, y0), (x1, y1) in zip(points, points[1:]):
        if x <= x1:
            u = 0.0 if x1 == x0 else (x - x0)/(x1 - x0)
            return y0 + (y1 - y0)*(1 - math.cos(math.pi*u))/2
    return points[-1][1]


def smooth(u):
    u = min(1.0, max(0.0, u))
    return u*u*(3 - 2*u)


def thigh_angle(gait, q):
    """Thigh angle (degrees, positive = forward) at leg phase q: linear through the stance, eased through the swing."""
    if q <= STANCE[gait]:
        return SWEEP[gait]*(1 - 2*q/STANCE[gait])
    return ease(CURVES[gait]['thigh'], q)


def arm_phase(gait, q):
    """Smooth counter-swing synchronized to contact and toe-off, without following the knee's recovery kick.

    Both halves meet with zero angular velocity. In the old clip the arms followed the thigh's overshoot and
    could suddenly snap backwards as the foot recovered; the reference keeps the elbows bent and pumps smoothly.
    """
    stance = STANCE[gait]
    return (math.cos(math.pi*q/stance) if q <= stance else
            -math.cos(math.pi*(q - stance)/(1 - stance)))


def gait_pose(gait, phase, amp=1.0):
    """Deltas {bone: [(frame, axis, degrees), ...]} of one gait at cycle phase 0..1 (right leg phase), amplitude
    0..1. frame is the bone whose posed orientation the axis is given in (None: model space)."""
    c = CURVES[gait]
    d = {}
    swing = {}
    for side, (thigh, knee, ankle) in LEGS.items():
        q = (phase + (0.0 if side == 'R' else 0.5)) % 1.0
        t, k, foot = thigh_angle(gait, q), ease(c['knee'], q), ease(c['ankle'], q)
        d[thigh] = [(PELVIS, (1, 0, 0), -amp*t)]
        d[knee] = [(PELVIS, (1, 0, 0), amp*k)]
        d[ankle] = [(PELVIS, (1, 0, 0), amp*(t - k + foot))]
        swing[side] = arm_phase(gait, q)
    lean16, lean17 = c['lean']
    d[PELVIS] = [(None, (0, 1, 0), -amp*c['pelvis']*swing['R'])]
    d[SPINE] = [(PELVIS, (1, 0, 0), amp*lean16), (None, (0, 1, 0), amp*c['pelvis']*swing['R'])]
    d[CHEST] = [(SPINE, (1, 0, 0), amp*lean17), (None, (0, 1, 0), amp*c['chest']*swing['R'])]
    # The gaze stays forward while the chest counter-rotates, instead of yawing with every footfall.
    d[NECK] = [(CHEST, (1, 0, 0), amp*c['head']/2), (None, (0, 1, 0), -amp*c['chest']*swing['R']/2)]
    d[HEAD] = [(NECK, (1, 0, 0), amp*c['head']/2), (None, (0, 1, 0), -amp*c['chest']*swing['R']/2)]
    elbow_rest, elbow_run = c['elbow']
    for side, (shoulder, elbow, _) in ARMS.items():
        down = c['arm_down']*(-1 if side == 'R' else 1)
        # Arms swing against the same-side leg; positive X swings an arm back.
        arm = amp*(c['arm_swing']*swing[side] - c['arm_forward'])
        d[shoulder] = [(CHEST, (0, 0, 1), down), (CHEST, (1, 0, 0), arm)]
        d[elbow] = [(CHEST, (1, 0, 0), -(elbow_rest + amp*(elbow_run - elbow_rest)))]
    return d


def stop_pose(u):
    """The brake at u = 0..1 of the stop clip: the right foot planted ahead and braced, the left trailing, the body
    leaning back; it settles to standing (arms down, legs straight) by the end."""
    k = 1 - smooth(u)
    d = {}
    for (thigh, knee, ankle), (t, n, a) in ((LEGS['R'], (30.0, 14.0, -12.0)), (LEGS['L'], (-24.0, 46.0, 18.0))):
        d[thigh] = [(PELVIS, (1, 0, 0), -k*t)]
        d[knee] = [(PELVIS, (1, 0, 0), k*n)]
        d[ankle] = [(PELVIS, (1, 0, 0), k*a)]
    d[PELVIS] = [(None, (1, 0, 0), -k*6.0)]
    d[SPINE] = [(None, (1, 0, 0), -k*4.0)]
    d[CHEST] = [(None, (1, 0, 0), -k*3.0)]
    d[NECK] = [(None, (1, 0, 0), k*4.0)]
    d[HEAD] = [(None, (1, 0, 0), k*3.0)]
    for side, (shoulder, elbow, _) in ARMS.items():
        down = 72.0*(-1 if side == 'R' else 1)  # preserve the existing brake pose independently of running
        d[shoulder] = [(CHEST, (0, 0, 1), down), (CHEST, (1, 0, 0), -k*(20.0 if side == 'R' else -10.0))]
        d[elbow] = [(CHEST, (1, 0, 0), -(18.0 + k*50.0))]
    return d


def sidestep_pose(side, phase):
    """A sidestep cycle toward the body's right (side +1, model -X) or left (-1), the torso facing forward.

    The leading leg lifts and steps out during the first half while the other leg carries the body; in the second
    half the trailing leg lifts and closes under the body. Thigh roll is about the forward axis (Z) in the pelvis
    frame: a positive roll moves the foot to the body's right."""
    # This side-step is intentionally independent of the forward walk/run polish.
    # Keep the existing sideways movement animation, including its sampling below.
    c = dict(lean=(3.0, 2.0), head=-2.0, arm_down=74.0, arm_forward=2.0, elbow=(18.0, 26.0))
    open_ = (1 - math.cos(2*math.pi*phase))/2           # 0 -> 1 (feet apart) -> 0
    lead, trail = ('R', 'L') if side > 0 else ('L', 'R')
    d = {}
    for leg, swing in ((lead, phase < 0.5), (trail, phase >= 0.5)):
        thigh, knee, ankle = LEGS[leg]
        u = (phase if leg == lead else phase - 0.5)/0.5
        lift = 32*math.sin(math.pi*u) if swing else 0.0
        roll = side*STEP*open_*(1 if leg == lead else -1)
        d[thigh] = [(PELVIS, (0, 0, 1), roll), (PELVIS, (1, 0, 0), -0.45*lift)]
        d[knee] = [(PELVIS, (1, 0, 0), 4 + lift)]
        d[ankle] = [(PELVIS, (1, 0, 0), -0.3*lift)]
    d[PELVIS] = [(None, (0, 0, 1), side*3*open_)]
    d[SPINE] = [(None, (1, 0, 0), c['lean'][0]), (None, (0, 0, 1), -side*2*open_)]
    d[CHEST] = [(None, (1, 0, 0), c['lean'][1])]
    d[NECK] = [(None, (1, 0, 0), c['head']/2)]
    d[HEAD] = [(None, (1, 0, 0), c['head']/2)]
    elbow = c['elbow'][1]
    for arm, (shoulder, elbow_bone, _) in ARMS.items():
        down = c['arm_down']*(-1 if arm == 'R' else 1)
        d[shoulder] = [(CHEST, (0, 0, 1), down), (CHEST, (1, 0, 0), -c['arm_forward'])]
        d[elbow_bone] = [(CHEST, (1, 0, 0), -elbow)]
    return d


def turned(deltas, sign):
    """The same pose with the upper body turned (sign +1: to the body's right) and banked toward that side."""
    out = {b: list(v) for b, v in deltas.items()}
    for bone, degrees in TURN.items():
        out.setdefault(bone, []).append((None, (0, 1, 0), sign*degrees))
    for bone, degrees in BANK.items():
        out[bone].append((None, (0, 0, 1), -sign*degrees))
    return out


def local_rotations(deltas):
    """Local quaternions of bones 1..54 for one pose. Each delta's axis is given in its frame bone's posed
    orientation (None: model space) and applied in the bone's parent frame; bind local rotations are identity."""
    world = {0: (0.0, 0.0, 0.0, 1.0)}
    local = {}
    for bone in range(1, 55):
        parent = PARENTS[bone]
        pw = world[parent]
        q = FIST.get(bone, (0.0, 0.0, 0.0, 1.0))
        for frame, axis, degrees in deltas.get(bone, ()):
            if degrees == 0: continue
            ref = (0.0, 0.0, 0.0, 1.0) if frame is None else world[frame]
            q = qmul(qaxis(qrot(qconj(pw), qrot(ref, axis)), degrees), q)
        local[bone] = qnorm(q)
        world[bone] = qnorm(qmul(pw, local[bone]))
    return local


# ------------------------------------------------------------------------------------------ clips

def key_times(frames, keys=KEYS):
    return tuple(int(math.floor(k*frames/(keys - 1) + .5)) for k in range(keys))


def walk_like(gait):
    return gait in WALKING


def pose_at(gait, anim, t):
    """Deltas of clip (gait, anim) at time t (60 Hz units)."""
    if anim in TURNED:
        base, sign = TURNED[anim]
        return turned(pose_at(gait, base, t), sign)
    frames = FRAMES[(gait, anim)]
    if gait == STOP and anim in (8, 9):
        return stop_pose(min(1.0, t/frames))
    if anim == 3:
        return gait_pose(gait, (t % frames)/frames)
    if anim == 8:
        return gait_pose(WALK, (t % frames)/frames)
    if anim == 9:
        return gait_pose(WALK, (1.0 - (t % frames)/frames) % 1.0)
    if anim in SIDESTEP:
        return sidestep_pose(SIDESTEP[anim], (t % frames)/frames)
    if anim == 2:
        u = t/frames
        if walk_like(gait):
            phase = (0.5 + 0.5*u) % 1.0
        else:
            phase = u % 1.0
        amp = 1.0 if t >= frames else 0.35 + 0.65*smooth(u)
        return gait_pose(gait, phase, amp)
    raise KeyError(anim)


def encode_clip(frames, tracks, root=None, root_tag=0):
    """Decoded native clip bytes. tracks: {bone: [(time, quaternion), ...]} (one key = constant)."""
    body = bytearray()
    offsets = [0]*BONES
    base = 6 + 2*BONES
    for bone in sorted(tracks):
        keys = tracks[bone]
        offsets[bone] = (base + len(body))//4
        if bone == 2 and root is not None:
            body += struct.pack('<HH', root_tag, len(root))
            for t, xyz in root:
                body += struct.pack('<3fIQ', *xyz, t, encode_quat(keys[0][1]))
            continue
        body += struct.pack('<HH', 1, len(keys))
        for _, q in keys: body += struct.pack('<Q', encode_quat(q))
        if len(keys) > 1:
            for t, _ in keys: body += struct.pack('<H', t)
        while len(body) % 4: body += b'\0'
    return struct.pack('<HH', FLAGS, frames) + b'\0\0' + struct.pack(f'<{BONES}H', *offsets) + bytes(body)


def compress_literal(decoded):
    out = bytearray()
    for i in range(0, len(decoded), 32767):
        chunk = decoded[i:i + 32767]
        out += bytes((0xFE, 0x7F, 0xFE, 0xFF)) + struct.pack('>H', len(chunk)) + chunk
    return struct.pack('<II', len(decoded), len(out)) + bytes(out)


def decompress_literal(packed):
    """Read our literal-only streams without importing the model preview tools."""
    size, length = struct.unpack_from('<II', packed)
    if length != len(packed)-8:
        raise ValueError('Invalid ground clip packed length')
    out, pos = bytearray(), 8
    while pos < len(packed):
        if packed[pos:pos+4] != bytes((0xFE, 0x7F, 0xFE, 0xFF)) or pos+6 > len(packed):
            raise ValueError('Invalid ground clip literal chunk')
        count = struct.unpack_from('>H', packed, pos+4)[0]
        pos += 6
        if not count or pos+count > len(packed):
            raise ValueError('Truncated ground clip literal chunk')
        out.extend(packed[pos:pos+count]); pos += count
    if len(out) != size:
        raise ValueError('Invalid ground clip decoded length')
    return bytes(out)


def canonical(gait, anim, profile='male', style='classic'):
    if profile not in ('male', 'female') or style not in ground_motion.STYLES:
        raise ValueError('Invalid ground motion profile')
    if gait == STOP:
        gait = RUN
    gait = WALK if gait in WALKING else RUN
    if anim in (8, 9):
        gait = WALK
    if gait == RUN or style != 'classic':
        profile = 'male'
    return gait, anim, profile


def authored_pose(gait, anim, t, profile='male', style='classic'):
    """Approved local rotations and leg-normalized hip motion at native time t.

Native start clips use the same continuous cycle as their loop. The game's
existing blend and our movement ramp ease the entry without distorting knees.
"""
    frames = FRAMES[(gait, anim)]
    gait, anim, profile = canonical(gait, anim, profile, style)
    base, turn = TURNED.get(anim, (anim, 0))
    phase = (t/frames) % 1.
    if base == 9:
        phase = (-phase) % 1.
    root, pose = ground_motion.sample('walk' if gait == WALK else 'run', phase, profile, style)
    if turn:
        for bone, angle in TURN.items():
            pose[bone] = qnorm(qmul(qaxis((0, 1, 0), turn*angle), pose[bone]))
    return root, pose


def motion_tag(gait, anim, profile, style='classic'):
    gait, anim, profile = canonical(gait, anim, profile, style)
    anim = TURNED.get(anim, (anim, 0))[0]
    # Starts and loops have the same root curve. Aliases use one immutable row.
    if anim == 2:
        anim = 3
    return 0x4000 + 2*(1 + (40 if profile == 'female' else 0) + gait*10 + anim-2)


def decoded_clip(gait, anim, profile='male', style='classic'):
    frames = FRAMES[(gait, anim)]
    authored = not (gait == STOP and anim in (8, 9)) and anim not in SIDESTEP
    # Preserve brake and sideways clip bytes exactly. Forward/backward motion
    # gets one quaternion sample per native unit (with native interpolation).
    keys = frames+1 if authored else (STOP_KEYS if gait == STOP else 17)
    times = key_times(frames, keys)
    if authored:
        samples = [authored_pose(gait, anim, t, profile, style) for t in times]
        poses = [p for _, p in samples]
        root = [(t, xyz) for t, (xyz, _) in zip(times, samples)]
    else:
        poses = [local_rotations(pose_at(gait, anim, t)) for t in times]
        root = None
    tracks = {}
    for bone in TRACKED:
        keys = [(t, p[bone]) for t, p in zip(times, poses)]
        packed = {encode_quat(q) for _, q in keys}
        tracks[bone] = keys[:1] if len(packed) == 1 else keys
    return encode_clip(frames, tracks, root, motion_tag(gait, anim, profile, style) if authored else 0)


@functools.lru_cache(maxsize=6)
def _built_set(profile, style):
    """{(set, anim): native clip bytes (8-byte size header + literal byte-pair stream)} for the five sets and anims
    2..11; SHARED entries are the very same bytes object as their source (one copy in RAM)."""
    out = {}
    for gait in SETS + (STOP,):
        for anim in IDS:
            key = (gait, anim)
            if key in SHARED: continue
            out[key] = compress_literal(decoded_clip(gait, anim, profile, style))
    for key, source in SHARED.items(): out[key] = out[source]
    return tuple(out.items())


def build_set(profile='male', style='classic'):
    """An independent directory of cached immutable clip bytes for this profile."""
    return dict(_built_set(profile, style))


def frames():
    return dict(FRAMES)


def ankle_z(gait, phase):
    """Goku's right ankle, model Z (forward/back), in the loop pose of a set at a leg phase (forward kinematics over
    GOKU_LEG with the clip's own local rotations)."""
    local = local_rotations(gait_pose(gait, phase))
    world, pos = (0.0, 0.0, 0.0, 1.0), (0.0, 0.0, 0.0)
    for bone in (1, 2, 3, 8, 9, 10, 11):
        if bone in GOKU_LEG:
            pos = tuple(p + v for p, v in zip(pos, qrot(world, GOKU_LEG[bone])))
        world = qnorm(qmul(world, local[bone]))
    return pos[2]


def stance_speed(gait):
    """Planted-foot speed of a set's loop, in leg lengths per animation unit: the ankle's travel from the first to the
    last stance key over the stance time (playback interpolates the keys, so this is the speed the feet have)."""
    frames = LOOP_FRAMES[gait]
    return abs(ankle_z(gait, 0.0) - ankle_z(gait, STANCE[gait]))/(STANCE[gait]*frames)/GOKU_LEG_LENGTH


STANCE_SPEED = {g: ground_motion.STANCE_TRAVEL['walk' if g in WALKING else 'run']/LOOP_FRAMES[g] for g in SETS}


def style_stance_speed(gait, style='classic'):
    return ground_motion.stance_travel('walk' if gait in WALKING else 'run', style)/LOOP_FRAMES[gait]


def digest(clips=None):
    clips = build_set() if clips is None else clips
    h = hashlib.sha256()
    for key in sorted(clips):
        h.update(struct.pack('<II', *key)); h.update(clips[key])
    return h.hexdigest()


CLIP_SET_SHA256 = '6192e3a6cd1d797e5e0f02a56ccc33f41e1042206a55f9f955dc107c80ebbe6b'


# ------------------------------------------------------------------------------------------ developer modes (ISO)

def _developer_module(name):
    """model_assets / model_animations, for the developer modes below only. Imported by name so that the player payload's
    import closure (build_player_bundle.closure follows every import statement) does not ship these modder tools: the
    match-time path (build_set, the clip constants) never needs them."""
    import importlib
    return importlib.import_module(name)


def rotated_bones(clips=None):
    """Bones 1..54 whose rotation differs from rest (identity) in some clip, with all their ancestors."""
    an = _developer_module('model_animations')
    clips = build_set() if clips is None else clips
    out = set()
    for data in clips.values():
        clip = an.AnimationClip.from_decoded(0, an.decompress_animation(data))
        for track in clip.tracks:
            if any(abs(k.rotation[3]) < 1 - 1e-6 for k in track.keys): out.add(track.bone_id)
    for bone in list(out):
        while PARENTS[bone] > 0:
            bone = PARENTS[bone]
            out.add(bone)
    return out


def compatible(parents, rotated=None):
    """(True, []) when a skeleton ({bone: parent}) poses like the standard biped under these clips: for every
    rotated bone it has, the nearest ancestor at or below 54 is PARENTS[bone] (bones above 54 in between never
    animate, so they only lengthen a chain). Bones the clips keep at rest may hang anywhere."""
    rotated = rotated_bones() if rotated is None else rotated
    bad = []
    for bone in sorted(rotated):
        if bone not in parents: continue
        q = parents[bone]
        while q > 54 and q in parents: q = parents[q]
        if q != PARENTS[bone]: bad.append(bone)
    return not bad, bad


def pmdl_parents(geometry):
    """{bone: parent} of a native PMDL skeleton (the part stack of 24C... model loading, as model_assets)."""
    if geometry[:4] != b'pmdl': raise ValueError('Expected native PMDL geometry')
    count, offset = struct.unpack_from('<I', geometry, 8)[0], struct.unpack_from('<I', geometry, 108)[0]
    stack, parents = [], {}
    for _ in range(count):
        size, pop, _, _, bone = struct.unpack_from('<IHHHH', geometry, offset)
        if size == 0: break      # some BT4 models end their part list early
        if size < 64: raise ValueError('Invalid skeleton part')
        parents[bone] = stack[-1] if stack else -1
        stack.append(bone)
        if pop: del stack[-pop:]
        offset += size
    return parents


def skeleton_parents(iso, character):
    """{bone: parent} of a character's base model on this tree's disc (BT4: bt4_resources' file numbering)."""
    ma = _developer_module('model_assets')
    try:
        import bt4_resources
        mesh = bt4_resources.request_files(character)[0]
    except ImportError:
        mesh = 10*character + 1424
    return pmdl_parents(ma.package_entry(ma.read_archive_entry(iso, mesh), 3))


def scan_parents(iso, characters):
    """{character: (compatible, bad bones) or an error string} for every readable character slot."""
    rotated = rotated_bones()
    out = {}
    for ch in characters:
        try:
            parents = skeleton_parents(iso, ch)
        except Exception as error:  # noqa: BLE001 - empty or menu-only slot
            out[ch] = repr(error)[:90]
            continue
        out[ch] = compatible(parents, rotated)
    return out


def extract_fist(iso, character=0, anim=3):
    ma = _developer_module('model_assets')
    an = _developer_module('model_animations')
    clip = an.AnimationBank.from_bytes(ma.read_animation_bank(iso, character)).clip(anim)
    pose = clip.evaluate(0)
    return {b: tuple(round(v, 6) if abs(v) > 2e-6 else 0.0 for v in pose[b].rotation) for b in FIST}


def render(iso, characters, out_dir, columns=8, size=180, keys=None, views=('side', 'front'), zoom=1.0):
    """Contact sheets (side and front views) of every clip on each character; developer check, read-only ISO."""
    from pathlib import Path
    import numpy as np
    from PIL import Image, ImageDraw
    ma = _developer_module('model_assets')
    an = _developer_module('model_animations')

    def matrix(q):
        x, y, z, w = q
        return np.array([[1-2*(y*y+z*z), 2*(x*y-z*w), 2*(x*z+y*w), 0], [2*(x*y+z*w), 1-2*(x*x+z*z), 2*(y*z-x*w), 0],
                         [2*(x*z-y*w), 2*(y*z+x*w), 1-2*(x*x+y*y), 0], [0, 0, 0, 1]], dtype=np.float64)

    def posed(asset, pose):
        world, remaining = {}, {b.native_id: b for b in asset.bones}
        leg = sum(float(np.linalg.norm(remaining[b].bind_translation)) for b in (10, 11) if b in remaining)
        while remaining:
            for key, bone in list(remaining.items()):
                if bone.parent_id in remaining: continue
                t = pose.get(key)
                local = matrix(t.rotation) if t else np.eye(4)
                local[:3, 3] = bone.bind_translation
                if key == 2 and t and t.translation is not None:
                    local[:3, 3] += np.asarray(t.translation)*leg
                world[key] = world.get(bone.parent_id, np.eye(4)) @ local
                del remaining[key]
        pos = np.column_stack((asset.positions, np.ones(len(asset.positions))))
        out = np.zeros((len(pos), 3))
        for bone in asset.bones:
            m = world[bone.native_id] @ np.linalg.inv(bone.bind_world)
            weight = np.sum(np.where(asset.bone_indices == bone.native_id, asset.bone_weights, 0), axis=1)
            mask = weight > 0
            if np.any(mask): out[mask] += (pos[mask] @ m.T)[:, :3]*weight[mask, None]
        return out

    def tile(asset, verts, view, size, scale, center, label):
        img = Image.new('RGB', (size, size), (235, 235, 235))
        d = ImageDraw.Draw(img)
        u, w, depth = ((verts[:, 2], verts[:, 1], verts[:, 0]) if view == 'side' else
                       (verts[:, 0], verts[:, 1], verts[:, 2]))
        px, py = (u - center[0])*scale + size/2, (w - center[1])*scale + size/2
        tri = asset.triangles
        for t in np.argsort(depth[tri].mean(axis=1)):
            a, b, c = tri[t]
            n = np.cross(verts[b] - verts[a], verts[c] - verts[a]); ln = np.linalg.norm(n)
            shade = 0.4 + 0.6*abs(n[0 if view == 'side' else 2]/ln) if ln > 1e-9 else 0.5
            col = int(60 + 150*shade)
            d.polygon([(px[a], py[a]), (px[b], py[b]), (px[c], py[c])], fill=(col, col - 20, col - 40))
        ground = (0 - center[1])*scale + size/2
        d.line([(0, ground), (size, ground)], fill=(200, 40, 40))
        d.text((3, 3), label, fill=(0, 0, 0))
        return img

    out_dir = Path(out_dir); out_dir.mkdir(parents=True, exist_ok=True)
    clips = build_set()
    written = []
    for ch in characters:
        asset = ma.load_character(iso, ch)
        bind = posed(asset, {})
        height = float(np.percentile(np.abs(bind[:, 1]), 99.5)) or 1.0
        scale = size*0.45*zoom/height
        rows = []
        for key in keys or [(RUN, a) for a in IDS] + [(WALK, a) for a in range(2, 8)]:
            clip = an.AnimationClip.from_decoded(key[1], an.decompress_animation(clips[key]))
            for view in views:
                tiles = []
                for k in range(columns):
                    t = clip.frame_count*k/(columns - 1)
                    verts = posed(asset, clip.evaluate(t))
                    label = f'c{ch} {GAITS[key[0]]} {key[1]} t{t:.1f}/{clip.frame_count} {view}'
                    tiles.append(tile(asset, verts, view, size, scale, (0.0, -height*0.5), label))
                row = Image.new('RGB', (size*columns, size), (255, 255, 255))
                for i, img in enumerate(tiles): row.paste(img, (size*i, 0))
                rows.append(row)
        for part in range(0, len(rows), 16):
            chunk = rows[part:part + 16]
            sheet = Image.new('RGB', (size*columns, size*len(chunk)), (255, 255, 255))
            for i, row in enumerate(chunk): sheet.paste(row, (0, size*i))
            path = out_dir/f'ground-clips-c{ch}-{part//16}.png'
            sheet.save(path)
            written.append(str(path))
    return written


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Developer checks of the ground clips (reads the ISO only).')
    parser.add_argument('--extract-fist', metavar='ISO')
    parser.add_argument('--scan-parents', metavar='ISO')
    parser.add_argument('--render', nargs=3, metavar=('ISO', 'OUT_DIR', 'CHARS'))
    parser.add_argument('--characters', default='0-160')
    parser.add_argument('--digest', action='store_true')
    args = parser.parse_args()
    if args.digest:
        clips = build_set()
        print(digest(clips), sum(len(v) for k, v in clips.items() if k not in SHARED), 'bytes')
    if args.extract_fist:
        for bone, q in extract_fist(args.extract_fist).items(): print(f'    {bone}: {q},')
    if args.scan_parents:
        lo, hi = (int(v) for v in args.characters.split('-'))
        result = scan_parents(args.scan_parents, range(lo, hi + 1))
        odd = {ch: v for ch, v in result.items() if not isinstance(v, tuple) or not v[0]}
        print(f'{len(result)} slots, {len(result) - len(odd)} compatible')
        for ch, v in sorted(odd.items()): print(ch, v)
    if args.render:
        iso, out, chars = args.render
        for path in render(iso, [int(c) for c in chars.split(',')], out): print(path)
