"""Developer-only conversion of approved motion samples into a stdlib runtime module.

The NPZ inputs are local review artifacts, not player payloads. Only rotations
and normalized hip displacement are retained; no mesh, texture, or ISO data.
Run after generating the approved revision-3 and October 9 C/D previews.
"""
from pathlib import Path
import base64
import hashlib
import struct
import textwrap
import zlib
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT/'bt3-multifighter/analysis/oct06-open-walk-preview/revision-3'
REFERENCE = 8.922
SOURCES = {'walk': INPUT/'walk.npz', 'run': INPUT/'run.npz', 'female_walk': INPUT/'female/walk.npz'}
MOCAP_INPUT = ROOT/'bt3-multifighter/analysis/oct09-gait-review-2'
MOCAP_SOURCES = {f'{style}_{gait}': MOCAP_INPUT/f'option-{option}'/f'{gait}.npz'
                 for style, option in (('natural', 'c'), ('fighter', 'd')) for gait in ('walk', 'run')}
HEADER = '''"""Selectable approved ground motion; Classic curves are Mannequiny v0.4.0.

Adapted animation data: GDQuest, Luciano Munoz and contributors, CC BY 4.0.
See assets/licenses/Mannequiny.txt. Generated by release_tools/bake_ground_motion.py.
This stores motion curves only. No game model, texture, or source GLB is included.
Natural/Fighter data is in ground_motion_cmu under its separate CMU terms.
"""
import base64
import functools
import math
import struct
import zlib
import ground_motion_cmu

REFERENCE = 8.922
STYLES = ('classic', 'natural', 'fighter')
SOURCE_GLB_SHA256 = '84caf77b520980448ca4fb3267b7272ba76fde20c0ce925f7a546c83fa5c01f8'
FEMALE_BT3 = (56, 57, 63, 75, 76, 102, 134, 156, 157)
FEMALE_BT4 = (56, 63, 75, 102, 104, 118, 119, 135, 154, 156, 165, 172, 176, 187, 198, 199, 200, 237)


def female_characters(bt4=False):
    return FEMALE_BT4 if bt4 else FEMALE_BT3


def slerp(a, b, t):
    dot = sum(x*y for x, y in zip(a, b))
    if dot < 0:
        b, dot = tuple(-v for v in b), -dot
    dot = min(1., max(-1., dot))
    if dot > .9995:
        q = tuple(x + (y-x)*t for x, y in zip(a, b))
        norm = math.sqrt(sum(v*v for v in q))
        return tuple(v/norm for v in q)
    angle = math.acos(dot)
    u, v = math.sin((1-t)*angle)/math.sin(angle), math.sin(t*angle)/math.sin(angle)
    return tuple(u*x + v*y for x, y in zip(a, b))


@functools.lru_cache(maxsize=7)
def samples(name):
    data = DATA if name in DATA else ground_motion_cmu.DATA
    counts = COUNTS if name in COUNTS else ground_motion_cmu.COUNTS
    raw = zlib.decompress(base64.b85decode(data[name]))
    if len(raw) != counts[name]*195*4:
        raise ValueError('Invalid authored ground motion length')
    out = []
    for values in struct.iter_unpack('<195f', raw):
        root = values[:3]
        rotations = tuple(tuple(values[3+b*4:7+b*4]) for b in range(48))
        out.append((root, rotations))
    return tuple(out)


def motion_name(gait, profile='male', style='classic'):
    if gait not in ('walk', 'run') or profile not in ('male', 'female') or style not in STYLES:
        raise ValueError('Invalid ground motion profile')
    if style != 'classic':
        return style + '_' + gait
    return 'female_walk' if profile == 'female' and gait == 'walk' else gait


def stance_travel(gait, style='classic'):
    name = motion_name(gait, style=style)
    return STANCE_TRAVEL[name] if style == 'classic' else ground_motion_cmu.STANCE_TRAVEL[name]


def source_speed(gait, style):
    return ground_motion_cmu.SOURCE_SPEED[motion_name(gait, style=style)]


def sample(gait, phase, profile='male', style='classic'):
    name = motion_name(gait, profile, style)
    rows = samples(name)
    x = (phase % 1.0)*len(rows)
    i, t = int(x), x-int(x)
    r0, q0 = rows[i]
    r1, q1 = rows[(i+1) % len(rows)]
    root = tuple(a+(b-a)*t for a, b in zip(r0, r1))
    rotations = {b: slerp(q0[b], q1[b], t) if b < 48 else (0., 0., 0., 1.) for b in range(1, 55)}
    return root, rotations

'''


def main():
    data, counts, hashes, stride = {}, {}, {}, {}
    for name, path in SOURCES.items():
        with np.load(path) as src:
            raw = np.column_stack((src['root_deltas']/REFERENCE, src['rotations'].reshape(-1, 192))).astype('<f4').tobytes()
            counts[name] = len(src['rotations'])
            hashes[name] = hashlib.sha256(raw).hexdigest()
            # In-place backward foot travel during the planted part of the
            # authored cycle, in leg lengths per cycle. Positive Z is backward.
            j = src['joints'][:, 11, :]
            speed = (np.roll(j[:, 2], -1)-j[:, 2])*len(j)
            contact = (speed > 0) & (j[:, 1] >= np.percentile(j[:, 1], 70))
            stride[name] = float(np.median(speed[contact])/REFERENCE)
            data[name] = base64.b85encode(zlib.compress(raw, 9)).decode('ascii')
    text = HEADER + 'COUNTS = ' + repr(counts) + '\nSAMPLE_SHA256 = ' + repr(hashes) + '\n'
    text += 'STANCE_TRAVEL = ' + repr(stride) + '\n\nDATA = {\n'
    for name, encoded in data.items():
        text += f'    {name!r}: (\n' + ''.join(f'        {line!r}\n' for line in textwrap.wrap(encoded, 100, break_on_hyphens=False)) + '    ),\n'
    text += '}\n'
    for folder in ('bt3-multifighter', 'bt4-multifighter'):
        (ROOT/folder/'tools/ground_motion.py').write_text(text, encoding='utf-8', newline='\n')
    print({'counts': counts, 'stance_travel': stride, 'module_bytes': len(text.encode())})
    data, counts, hashes, stride, speed = {}, {}, {}, {}, {}
    for name, path in MOCAP_SOURCES.items():
        with np.load(path) as src:
            rotations, roots = src['rotations'], src['root_deltas']/REFERENCE
            if rotations.shape != (len(roots), 48, 4) or not np.isfinite(rotations).all() or not np.isfinite(roots).all():
                raise ValueError(f'Invalid approved motion {name}')
            if not np.allclose(np.linalg.norm(rotations, axis=2), 1., atol=1e-5):
                raise ValueError(f'Non-unit rotation in {name}')
            raw = np.column_stack((roots, rotations.reshape(-1, 192))).astype('<f4').tobytes()
            counts[name] = len(rotations)
            hashes[name] = hashlib.sha256(raw).hexdigest()
            # These reviews were authored with explicit heel/sole/toe anchors
            # against a moving floor. Preserve that travel, not an estimate
            # based only on the rolling ankle's instantaneous velocity.
            stride[name] = float(src['speed']*src['duration']/REFERENCE)
            speed[name] = float(src['speed'])
            data[name] = base64.b85encode(zlib.compress(raw, 9)).decode('ascii')
    text = '''"""Natural and Fighter walking/running motion data.

Adapted from CMU Graphics Lab motion capture, MotionBuilder BVH conversion
by Bruce Hahne. Animation data is under CMU's separate reuse terms, NOT GPL
or CC0. See assets/licenses/CMU-Motion-Capture.txt and CMU-READMEFIRST.txt.
Generated by release_tools/bake_ground_motion.py from approved C/D reviews.
Only normalized motion samples are included; no game model or texture.
"""
'''
    text += 'COUNTS = ' + repr(counts) + '\nSAMPLE_SHA256 = ' + repr(hashes) + '\n'
    text += 'SOURCE_SPEED = ' + repr(speed) + '\n'
    text += 'STANCE_TRAVEL = ' + repr(stride) + '\n\nDATA = {\n'
    for name, encoded in data.items():
        text += f'    {name!r}: (\n' + ''.join(f'        {line!r}\n' for line in textwrap.wrap(encoded, 100, break_on_hyphens=False)) + '    ),\n'
    text += '}\n'
    for folder in ('bt3-multifighter', 'bt4-multifighter'):
        (ROOT/folder/'tools/ground_motion_cmu.py').write_text(text, encoding='utf-8', newline='\n')
    print({'cmu_counts': counts, 'stance_travel': stride, 'module_bytes': len(text.encode())})


if __name__ == '__main__':
    main()
