"""Generate bt3-multifighter/tools/bt3_english_names.json: the English names and forms of the 161 BT3 fighters.

The Japanese disc (SLPS-25815, Sparking! Meteor) has a Japanese-only text set, and the mod draws names with fonts
that have no Japanese glyphs (the PC fonts of the loading screens and settings, the kill feed's own 5x7 glyphs). Its
fighters keep the USA roster order and IDs, so the bt3-jpn adapter takes their English names from this table
(regional.english_names) and only the portraits from the disc. The table is read from the USA disc's English text
set (AFS1 index 450 = file 451, package 1 parts 29/30), with the extractor the USA installation uses
(extract_loading_assets.english_label). Names and forms only: no portraits, art or other game data.

usage: python -B release_tools/build_english_names.py [--iso USA.iso] [--out FILE] [--check]
--check regenerates in memory and exits 1 when the table is stale. The ISO is opened read-only.
"""
import argparse
import hashlib
import json
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
TOOLS = ROOT / 'bt3-multifighter' / 'tools'
OUT = TOOLS / 'bt3_english_names.json'
USA_ISO = ROOT / 'games' / 'Dragon Ball Z - Budokai Tenkaichi 3 (USA) (En,Ja).iso'
FIGHTERS = 161


def text_set(iso):
    """AFS1 index 450 (global file 451) of the USA disc, read-only."""
    import pycdlib
    image = pycdlib.PyCdlib()
    image.open(str(iso))
    try:
        import io
        out = io.BytesIO(); image.get_file_from_iso_fp(out, iso_path='/SYSTEM.CNF;1')
        if b'SLUS_216.78' not in out.getvalue():
            raise SystemExit(f'{iso} is not the USA disc (SLUS_216.78)')
        with image.open_file_from_iso(iso_path='/DATA/PZS3US1.AFS;1') as stream:
            magic, count = struct.unpack('<4sI', stream.read(8))
            if magic != b'AFS\0' or count != 3399:
                raise SystemExit('Expected the USA AFS1 archive (3399 files)')
            table = stream.read(count * 8)
            offset, size = struct.unpack_from('<II', table, 450 * 8)
            stream.seek(offset)
            return stream.read(size)
    finally:
        image.close()


def build(iso):
    sys.path.insert(0, str(TOOLS))
    import extract_loading_assets as x
    raw = text_set(iso)
    ui = x.package(x.unpack_bpe(x.package(raw)[1]))
    names, forms = x.package(ui[29]), x.package(ui[30])
    rows = []
    for index in range(FIGHTERS):
        base, form = x.english_label(names[index]), x.english_label(forms[index])
        if not base:
            raise SystemExit(f'Empty English name for fighter {index}')
        rows.append(dict(character_id=index, base_name=base, form=form))
    if rows[0]['base_name'] != 'Goku (Early)' or rows[55]['base_name'] != 'Hercule' or \
            rows[133]['form'] != 'Legendary Super Saiyan':
        raise SystemExit('Character identity validation failed')
    return dict(schema=1, about='English names and forms of the 161 BT3 fighters (USA disc SLUS-21678 text set, file '
                                '451, package 1 parts 29/30), used for discs whose own text set is not English '
                                '(the Japanese SLPS-25815). Generated by release_tools/build_english_names.py.',
                source_sha256=hashlib.sha256(raw).hexdigest(), characters=rows)


def render(doc):
    return json.dumps(doc, indent=1, ensure_ascii=False) + '\n'


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--iso', default=str(USA_ISO)); ap.add_argument('--out', default=str(OUT))
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args(argv)
    text = render(build(Path(args.iso)))
    out = Path(args.out)
    if args.check:
        if not out.is_file() or out.read_text(encoding='utf-8') != text:
            print(f'{out} is stale; run build_english_names.py', file=sys.stderr)
            return 1
        print(f'{out} is current')
        return 0
    out.write_text(text, encoding='utf-8', newline='\n')
    print(f'wrote {out} ({FIGHTERS} fighters)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
